# Generated by Django 5.0.4 on 2024-04-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('sujet', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('telephone', models.IntegerField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
